
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;

        ///  &lt;brick&gt;
        ///    &lt;x&gt;4&lt;/x&gt;
        ///    &lt;y&gt;4&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;59&lt;/x&gt;
        ///    &lt;y&gt;4&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;114&lt;/x&gt;
        ///    &lt;y&gt;4&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;169&lt;/x&gt;
        ///    &lt;y&gt;4&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;224&lt;/x&gt;
        ///    &lt;y&gt;4&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;279&lt;/x&gt;
        ///    &lt;y&gt;4&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;334&lt;/x&gt;
        ///    &lt;y&gt;4&lt;/y&gt;
        ///    &lt;hp&gt;3&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level3 {
            get {
                return ResourceManager.GetString("level3", resourceCulture
        ///
        ///  &lt;brick&gt;
        ///    &lt;x&gt;500&lt;/x&gt;
        ///    &lt;y&gt;50&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///
        ///  &lt;brick&gt;
        ///    &lt;x&gt;400&lt;/x&gt;
        ///    &lt;y&gt;40&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///
        ///  &lt;brick&gt;
        ///    &lt;x&gt;300&lt;/x&gt;
        ///    &lt;y&gt;30&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///
        ///  &lt;brick&gt;
        ///    &lt;x&gt;200&lt;/x&gt;
        ///    &lt;y&gt;20&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///
        ///  &lt;brick&gt;
        ///    &lt;x&gt;100&lt;/x&gt;
        ///    &lt;y&gt;10&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///
        ///  &lt;brick&gt;
        ///    &lt;x&gt;50&lt;/x&gt;
        ///    &lt;y&gt;5&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///
        ///&lt;/level&gt;
        ///.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Level&gt;
        ///  
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;337&lt;/x&gt;
        ///    &lt;y&gt; 42&lt;/y&gt;
        ///    &lt;hp&gt;2 &lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;262 &lt;/x&gt;
        ///    &lt;y&gt;74&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;405&lt;/x&gt;
        ///    &lt;y&gt;74&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///  
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;46&lt;/x&gt;
        ///    &lt;y&gt;125&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///  
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;157&lt;/x&gt;
        ///    &lt;y&gt;125&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///  
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;262&lt;/x&gt;
        ///    &lt;y&gt;125&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///  
        ///  &lt;Brick&gt;     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Level&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt; 238&lt;/x&gt;
        ///    &lt;y&gt;43&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;302&lt;/x&gt;
        ///    &lt;y&gt;43&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;358&lt;/x&gt;
        ///    &lt;y&gt;43&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;419&lt;/x&gt;
        ///    &lt;y&gt;43&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;473&lt;/x&gt;
        ///    &lt;y&gt;74&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;502&lt;/x&gt;
        ///    &lt;y&gt;105&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;502&lt;/x&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level4 {
            get {
                return ResourceManager.GetString("level4", resourceCulture);

            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;

        ///  &lt;brick&gt;
        ///    &lt;x&gt;17&lt;/x&gt;
        ///    &lt;y&gt;4&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;127&lt;/x&gt;
        ///    &lt;y&gt;4&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;237&lt;/x&gt;
        ///    &lt;y&gt;4&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;347&lt;/x&gt;
        ///    &lt;y&gt;4&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;457&lt;/x&gt;
        ///    &lt;y&gt;4&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;567&lt;/x&gt;
        ///    &lt;y&gt;4&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;677&lt;/x&gt;
        ///    &lt;y&gt;4&lt;/y&gt;
        ///    &lt;hp&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level7 {
            get {
                return ResourceManager.GetString("level7", resourceCulture);

        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;3&lt;/x&gt;
        ///    &lt;y&gt;2&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;59&lt;/x&gt;
        ///    &lt;y&gt;2&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;115&lt;/x&gt;
        ///    &lt;y&gt;2&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;171&lt;/x&gt;
        ///    &lt;y&gt;2&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;227&lt;/x&gt;
        ///    &lt;y&gt;2&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;283&lt;/x&gt;
        ///    &lt;y&gt;2&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/Brick&gt;
        ///
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;339&lt;/x&gt;
        ///    &lt;y&gt;2&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level6 {
            get {
                return ResourceManager.GetString("level6", resourceCulture);
            }
        }
    }
}
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///
        ///  &lt;brick&gt;
        ///    &lt;x&gt;500&lt;/x&gt;
        ///    &lt;y&gt;50&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///
        ///  &lt;brick&gt;
        ///    &lt;x&gt;400&lt;/x&gt;
        ///    &lt;y&gt;40&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///
        ///  &lt;brick&gt;
        ///    &lt;x&gt;300&lt;/x&gt;
        ///    &lt;y&gt;30&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///
        ///  &lt;brick&gt;
        ///    &lt;x&gt;200&lt;/x&gt;
        ///    &lt;y&gt;20&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///
        ///  &lt;brick&gt;
        ///    &lt;x&gt;100&lt;/x&gt;
        ///    &lt;y&gt;10&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///
        ///  &lt;brick&gt;
        ///    &lt;x&gt;50&lt;/x&gt;
        ///    &lt;y&gt;5&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///
        ///&lt;/level&gt;
        ///.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;400&lt;/x&gt;
        ///    &lt;y&gt;25&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///    &lt;colour&gt;Green&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;400&lt;/x&gt;
        ///    &lt;y&gt;56&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///    &lt;colour&gt;Green&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;400&lt;/x&gt;
        ///    &lt;y&gt;90&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///    &lt;colour&gt;Green&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;432&lt;/x&gt;
        ///    &lt;y&gt;118&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///    &lt;colour&gt;Green&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;465&lt;/x&gt;
        ///    &lt;y&gt;149&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///    &lt;colou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level5 {
            get {
                return ResourceManager.GetString("level5", resourceCulture);

            }
        }
    }
}
